language: rust
cache: cargo
rust:
  - stable
  - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose

jobs:
  allow_failures:
    rust: stable