[package]
name = "monzo-lib"
version = "0.0.0"
authors = ["Daniel Eades <danieleades@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.10.0-alpha.1", features = ["json"] }
chrono = {version = "0.4.9", features = ["serde"] }
serde = { version = "1.0.101", features = ["derive"] }
