[package]
name = "monzo-lib"
version = "0.0.1"
authors = ["Daniel Eades <danieleades@hotmail.com>"]
edition = "2018"
description = "async Monzo client in pure rust."
readme = "README.md"
keywords = ["monzo", "mondo", "async", "client"]
homepage = "https://github.com/danieleades/monzo-lib"
repository = "https://github.com/danieleades/monzo-lib"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "danieleades/monzo-lib" }
maintenance = { status="actively-developed" }

[dependencies]
reqwest = {version = "0.10.0-alpha.1", features = ["json"] }
chrono = {version = "0.4.9", features = ["serde"] }
serde = { version = "1.0.101", features = ["derive"] }
pin-project = "0.4.4"

[dev-dependencies]
tokio = "0.2.0-alpha.6"
