[package]
name = "monzo-lib"
version = "0.0.3"
authors = ["Daniel Eades <danieleades@hotmail.com>"]
edition = "2018"
description = "async Monzo client in pure rust."
readme = "README.md"
keywords = ["monzo", "mondo", "async", "client"]
homepage = "https://github.com/danieleades/monzo-lib"
repository = "https://github.com/danieleades/monzo-lib"
license = "Apache-2.0"

[lib]
name = "monzo"

[badges]
travis-ci = { repository = "danieleades/monzo-lib" }
maintenance = { status = "actively-developed" }

[dependencies]
reqwest = { git = "https://github.com/seanmonstar/reqwest", features = ["json", "stream"] }
chrono = { version = "0.4.10", features = ["serde"] }
serde = { version = "1.0.104", features = ["derive"] }
futures-util = "0.3.1"
rand = "0.7.2"
serde_json = "1.0.44"

[dev-dependencies]
tokio = { version = "0.2.6", features = ["macros"] }
